site_name: Lance-Ray Documentation

nav:
  - Home: index.md
  - Installation: installation.md
  - API Reference: api_reference.md
  - Examples: examples.md
  - Development: development.md
  - Contributing: contributing.md
  - License: LICENSE.md