site_name: Lance-Ray Documentation

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Quick Start: getting-started/quick-start.md
  - Usage: usage.md
  - Contributing: contributing.md
