name: PR Checks

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  # Required for PR comments
  pull-requests: write
  # Required for storing benchmark results
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Install dev dependencies
        run: uv sync --extra dev
      - name: Run ruff check
        run: uv run ruff check

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Install dev dependencies
        run: uv sync --extra dev
      - name: Run tests
        run: uv run pytest -v
